import os, sys, re, json

repo_dir = os.path.abspath('repo')
pmdred_dir = '/tmp/pmd-red'
report_path = os.path.join(repo_dir, 'docs', 'ANALYSE_MASTERCLASS_RAYQUAZA_METEORITE.md')

with open(report_path, 'w', encoding='utf-8') as out:
    out.write("# MASTERCLASS CINÉMATIQUE : LA MÉTÉORITE ET RAYQUAZA\n\n")
    out.write("> **Document d'architecture de mise en scène pour New Era**\n")
    out.write("> Basé sur l'extraction des comportements GBA de *Pokémon Donjon Mystère : Équipe de Secours Rouge*.\n\n")
    
    out.write("## 1. La Météorite (Objet Céleste et Ciel)\n\n")
    out.write("### Comment Chunsoft a géré la Météorite sur GBA :\n")
    out.write("L'analyse du code source (`ground_data_a04p01_station.h`, `ground_data_t01p01_station.h`) montre que la Météorite n'est **pas** un sprite (OBJ) classique comme un personnage. La GBA utilisait des calques de fond (Background Layers / `BPL`) pour le ciel, et des effets de scrolling. La météorite était rendue via :\n")
    out.write("- **Un Background Scrolling (MapBG)** : Le ciel étoilé défile en arrière-plan.\n")
    out.write("- **Manipulation de Palettes (`FLASH_TO`)** : L'approche de la météorite assombrit le ciel artificiellement. La macro `FLASH_TO(TRUE, PALUTIL_KIND_05, 2, RGB_U32(0x80, 0x80, 0x10))` peint l'écran en jaune maladif, traduisant la chaleur et la proximité de l'astre, suivie de noir (`0x000000`) pour l'ombre gigantesque.\n")
    out.write("- **SFX (Sons)** : Un grondement constant (`SE_PLAY`) couplé à un `SCREEN_SHAKE`.\n\n")
    
    out.write("### ⚡ Adaptation pour RogueEssence (New Era)\n")
    out.write("RogueEssence gère beaucoup mieux ce genre de scène. Tu n'as pas besoin de tricher avec des palettes : \n")
    out.write("1. **Asset Visuel** : Utiliser un `GroundObject` géant (ex: un sprite de Météorite de 256x256) avec l'animation d'une boule de feu.\n")
    out.write("2. **Trajectoire (Script)** : \n")
    out.write("   ```lua\n")
    out.write("   local meteor = GROUND:SpawnerSetSpawn('Meteor_Spawner')\n")
    out.write("   GROUND:MoveToPosition(meteor, target_X, target_Y, false, speed)\n")
    out.write("   ```\n")
    out.write("3. **Ciel Dynamique** : Changer l'ambiance avec `GAME:SetMapBG('sky_meteor')` et appliquer une teinte rouge/jaune avec `GAME:FadeOut(true, speed)` ou utiliser une météo custom.\n\n")

    out.write("## 2. Apparition de Rayquaza (Tour Céleste `D13P03`)\n\n")
    out.write("### Extraction de la Mise en scène originale :\n")
    out.write("- **Position d'apparition** : Rayquaza (`NPC_RAYQUAZA 2`) n'est pas posé sur la carte. Il spawn virtuellement depuis le bord supérieur droit de l'écran en utilisant `PORTRAIT(PLACEMENT_MIDRIGHT_TOP_FLIP, NPC_RAYQUAZA, 0)` pour introduire sa voix de nulle part.\n")
    out.write("- **Caméra** : `CAMERA_INIT_PAN()` -> La caméra commence dans les nuages (fond) et redescend brutalement vers les héros au sol au moment où la BGM commence.\n")
    out.write("- **Musique** : La musique s'arrête net au sommet. Un silence pesant de 60 frames. Puis, `BGM_SWITCH(MUS_RAYQUAZAS_DOMAIN)` explose littéralement.\n")
    out.write("- **Animation** : Rayquaza descend du ciel (mouvement vertical) pendant que les héros utilisent l'animation `CALL_SCRIPT(JUMP_SURPRISE_FUNC)`.\n\n")

    out.write("### ⚡ Adaptation pour RogueEssence (New Era)\n")
    out.write("1. Placer un `Spawner` pour Rayquaza en dehors de l'écran (ex: `Y = -100`).\n")
    out.write("2. Stopper la musique de donjon dès que le joueur touche le trigger d'entrée.\n")
    out.write("3. Lancer un rugissement SFX (ex: `SE_RAYQUAZA_CRY`), puis `GAME:PlayBGM('Rayquazas Domain', true)`.\n")
    out.write("4. Descendre la caméra lentement vers le héros `GAME:MoveCamera(...)`.\n\n")

    out.write("## 3. Impact et Destruction (Le Climax)\n\n")
    out.write("### Extraction de la GBA :\n")
    out.write("C'est la séquence la plus brutale. L'Ultralaser (Hyper Beam) est traduit par une succession hystérique de flashs blancs.\n")
    out.write("```c\n")
    out.write("MSG_NPC(NPC_RAYQUAZA, \" Take charge of your destiny!\")\n")
    out.write("FLASH_TO(TRUE, PALUTIL_KIND_05, 8, RGB_U32(0xFF, 0xFF, 0xFF)) // Blanc éblouissant (8 frames)\n")
    out.write("FLASH_FROM(FALSE, PALUTIL_KIND_05, 16, RGB_U32(0xFF, 0xFF, 0xFF)) // Retour au jeu (16 frames)\n")
    out.write("FLASH_TO(TRUE, PALUTIL_KIND_05, 4, RGB_U32(0xFF, 0xFF, 0xFF)) // Blanc aveuglant et rapide\n")
    out.write("CALL_SCRIPT(SHOCK_FUNC) // Tremblement de terre max\n")
    out.write("BGM_FADEOUT(120) // La musique coupe lentement pendant la lumière blanche\n")
    out.write("```\n")
    out.write("Le jeu ne montre pas l'explosion en 3D. Il plonge le joueur dans un blanc total pendant 60 frames, secoue l'écran, et quand l'écran redevient noir (ou normal), le héros se réveille dans les limbes (rêve de Gardevoir).\n\n")

    out.write("### ⚡ Adaptation pour RogueEssence (New Era)\n")
    out.write("RogueEssence permet de faire *bien mieux* visuellement tout en gardant cette brutalité :\n")
    out.write("1. **L'Ultralaser (Particules)** : Utiliser un `Emitter` continu attaché à la bouche de Rayquaza pointé vers le ciel, ou une animation de sort (Spell Anim) gigantesque.\n")
    out.write("2. **Le Flash (Sensorialité)** :\n")
    out.write("   ```lua\n")
    out.write("   -- L'écran devient blanc instantanément\n")
    out.write("   GAME:FadeOut(true, 5)\n")
    out.write("   -- Tremblement violent pendant l'écran blanc\n")
    out.write("   GAME:WaitFrames(20)\n")
    out.write("   -- Disparition du bruit de laser, bruit d'explosion sourde\n")
    out.write("   SOUND:PlayBattleSE('EVT_Explosion_Huge')\n")
    out.write("   GAME:WaitFrames(120) -- 2 secondes de blanc pesant\n")
    out.write("   -- Transition silencieuse vers la scène suivante (Les Limbes)\n")
    out.write("   GAME:EnterGroundMap('limbes_hero', 'Spawn')\n")
    out.write("   ```\n\n")

    out.write("---\n")
    out.write("*Cette séquence est la référence maîtresse (Masterclass) de New Era. Toute future destruction de ville, éveil de légendaire (ex: Groudon ou Arceus), ou effondrement scénaristique devra s'appuyer sur ces mécaniques de Flashs blancs, Tremblements (Camera Shake) et Ruptures de rythme musical (BGM_STOP -> Silence -> Musique épique).*")
    
print("Masterclass d'analyse générée.")
